#!/usr/bin/env bash

cat > index.md <<HERE
---
title: The Meticulous US Intern's Guide
date: 2017-05-12
description: A comprehensive Canadian student's guide to internships in the US.
layout: post
---

<!-- this file is automatically generated from INTERN101.md by build.sh -->

HERE
sed -e 's/^\(\s*\*\) \[[ x]\]\(.*\)/\1 <label><input type="checkbox"><span>\2<\/span><\/label>/' INTERN101.md >> index.md
cat INTERN101-addendum.md >> index.md